# Generated by Django 5.2.8 on 2025-12-20 04:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "Kurs"},
        ),
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["number"], "verbose_name_plural": "Gün"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Fakultet"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name_plural": "Topar"},
        ),
        migrations.AlterModelOptions(
            name="lessonnumber",
            options={"verbose_name_plural": "Sapak nomer"},
        ),
        migrations.AlterModelOptions(
            name="lessontype",
            options={"verbose_name_plural": "Sapak görnüşi"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name_plural": "Sapaklaryň ady"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "Mugallym"},
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={
                "ordering": ["week__number", "day__number", "lesson_number__number"],
                "verbose_name_plural": "Sapak tertibi",
            },
        ),
        migrations.AlterModelOptions(
            name="week",
            options={"verbose_name_plural": "Hepde"},
        ),
    ]
