# Generated by Django 5.2.8 on 2025-12-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_alter_course_options_alter_day_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetableentry",
            name="teacher",
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="timetable_entries", to="timetable.teacher"
            ),
        ),
    ]
